const CONFIG={fallbackLocation:{lat:18.5204,lon:73.8567}};
const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,"0");
let map,marker,seenIds=new Set();
function tickClock(){const n=new Date();$("clockTime").textContent=`${pad(n.getHours())}:${pad(n.getMinutes())}:${pad(n.getSeconds())}`;$("clockDate").textContent=n.toLocaleDateString(undefined,{year:"numeric",month:"short",day:"2-digit"});}setInterval(tickClock,1000);tickClock();
function connectionState(online){$("connectivityChip").classList.toggle("online",online);$("connectivityChip").classList.toggle("offline",!online);$("connectivityText").textContent=online?"ONLINE":"OFFLINE";$("footerConn").textContent=online?"Online":"Offline";}connectionState(navigator.onLine);addEventListener("online",()=>connectionState(true));addEventListener("offline",()=>connectionState(false));
function initMap(lat,lon){map=L.map("mapView").setView([lat,lon],15);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(map);marker=L.marker([lat,lon]).addTo(map).bindPopup("Mobile / robot location");updateLocation(lat,lon);}
function updateLocation(lat,lon){if(lat==null||lon==null)return;if(!map)initMap(lat,lon);else{marker.setLatLng([lat,lon]);map.panTo([lat,lon]);}$("coordsText").textContent=`lat ${lat.toFixed(5)}, lon ${lon.toFixed(5)}`;fetchWeather(lat,lon);}
function setPipelineState(node,on,alert=false){const el=document.querySelector(`.pipe-node[data-node="${node}"]`);if(!el)return;el.classList.toggle("active",on);el.classList.toggle("alert",alert&&on);if(on)setTimeout(()=>el.classList.remove("active","alert"),1200);}
function setDetectionState(id,active,value){const el=$(id);el.classList.toggle("flagged",active);el.querySelector(".detect-value").textContent=value;}
function logDetection(text,time){const log=$("detectLog"),li=document.createElement("li");li.innerHTML=`<span>${time||new Date().toLocaleTimeString()}</span> — ${text}`;log.prepend(li);while(log.children.length>50)log.removeChild(log.lastChild);}
function renderBattery(v){if(v==null)return;$("batteryFill").style.width=`${v}%`;$("batteryValue").textContent=`${v.toFixed(0)}%`;}
function renderEvent(e,history=false){if(e.id&&seenIds.has(e.id))return;if(e.id)seenIds.add(e.id);["robot","camera","ai","dash"].forEach(x=>setPipelineState(x,true));if(e.latitude!=null){updateLocation(e.latitude,e.longitude);setPipelineState("gps",true);}renderBattery(e.battery_pct);if(e.temperature_c!=null)$("tempValue").textContent=`${e.temperature_c.toFixed(1)} °C`;$("criticalScore").textContent=`CRITICAL ${e.critical_score}%`;const ds=e.detections||[],person=ds.filter(x=>x.label==="person"),vehicle=ds.filter(x=>["car","truck","bus","motorcycle"].includes(x.label)),hazard=ds.filter(x=>["fire","smoke","knife"].includes(x.label));setDetectionState("det-object",ds.length>0,String(ds.length));setDetectionState("det-human",person.length>0,person.length?`DETECTED ${person[0].confidence}%`:"CLEAR");setDetectionState("det-vehicle",vehicle.length>0,vehicle.length?"DETECTED":"CLEAR");setDetectionState("det-hazard",hazard.length>0,hazard.length?"HAZARD":"CLEAR");if(!history)logDetection(ds.length?ds.map(x=>`${x.label} (${x.confidence}%)`).join(", "):"No object detected",new Date(e.created_at).toLocaleTimeString());if(e.priority==="CRITICAL"){triggerAlert(`Critical YOLO score ${e.critical_score}%`);setPipelineState("alert",true,true);}}
function refreshFeed(){$("camVideo").src=`/api/live-frame?t=${Date.now()}`;}setInterval(refreshFeed,700);
async function loadHistory(){try{const items=await fetch("/api/history").then(r=>r.json());items.reverse().forEach(x=>{renderEvent(x,true);logDetection((x.detections||[]).map(d=>`${d.label} (${d.confidence}%)`).join(", ")||"No object",new Date(x.created_at).toLocaleTimeString());});}catch{}}loadHistory();
function connect(){const protocol=location.protocol==="https:"?"wss":"ws",ws=new WebSocket(`${protocol}://${location.host}/ws/dashboard`);ws.onmessage=x=>{renderEvent(JSON.parse(x.data));refreshFeed();};ws.onclose=()=>setTimeout(connect,2000);}connect();
const startTime=Date.now();setInterval(()=>{const e=Math.floor((Date.now()-startTime)/1000);$("uptimeValue").textContent=`${pad(Math.floor(e/3600))}:${pad(Math.floor(e%3600/60))}:${pad(e%60)}`;},1000);
const WEATHER_CODES={0:"Clear",1:"Mainly clear",2:"Cloudy",3:"Overcast",61:"Light rain",63:"Rain",65:"Heavy rain",95:"Storm"};async function fetchWeather(lat,lon){try{const d=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current_weather=true`).then(r=>r.json()),c=d.current_weather;if(c){$("weatherValue").textContent=WEATHER_CODES[c.weathercode]||"—";$("ambientValue").textContent=`${c.temperature.toFixed(1)} °C`;}}catch{$("weatherValue").textContent="Unavailable";}}
const sosPanel=$("sosPanel"),sosButton=$("sosButton"),sosStatusText=$("sosStatusText");let alertActive=false;function triggerAlert(reason){alertActive=true;sosPanel.classList.add("active");sosStatusText.textContent=`ACTIVE ALERT — ${reason}`;sosButton.textContent="CANCEL SOS";}function clearAlert(){alertActive=false;sosPanel.classList.remove("active");sosStatusText.textContent="SYSTEM NOMINAL — NO ACTIVE ALERTS";sosButton.textContent="TRIGGER SOS";}sosButton.onclick=()=>alertActive?clearAlert():triggerAlert(`Manual SOS at ${new Date().toLocaleTimeString()}`);
initMap(CONFIG.fallbackLocation.lat,CONFIG.fallbackLocation.lon);fetchWeather(CONFIG.fallbackLocation.lat,CONFIG.fallbackLocation.lon);
